AppBundle\Entity\Ditte:
    type: entity
    table: ditte
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idUtente:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_utente
        idCategoria:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_categoria
        ragioneSoc:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: ragione_soc
        indirizzo:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        cap:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: ''
        citta:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        telefono:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        piva:
            type: string
            nullable: false
            length: 11
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
