AppBundle\Entity\Utenti:
    type: entity
    table: utenti
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idDitta:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: id_ditta
        user:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        permission:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
